_BASE_: ../Base-COSINE.yaml
MODEL:
  META_ARCHITECTURE: "COSINEFCCLIP"
  COSINE:
    GEOMETRIC_ENSEMBLE_ALPHA: 0.4
    GEOMETRIC_ENSEMBLE_BETA: 0.8
  ROI_HEADS:
    NUM_CLASSES: 1230
DATASETS:
  TRAIN: ("lvis_v0.5_train_shots",)
  TEST: ("lvis_v0.5_val",)
OUTPUT_DIR: "outputs/fsod/cosine/lvis_all"